#!/bin/bash

# variables

TITLE1=$1
TITLE2=$2
TITLE3=$3
TITLE4=$4
Release=$5
YEAR=$(date +"%Y")
DATE=$(date +"%x")
CODEDATE=$(date +"nxI-%Y%m%d") 

TIME1=`soxi -d "$TITLE1".wav`
TIME2=`soxi -d "$TITLE2".wav`
TIME3=`soxi -d "$TITLE3".wav`
TIME4=`soxi -d "$TITLE4".wav`

TOTALTIME=`soxi -T -d "$TITLE1".wav "$TITLE2".wav "$TITLE3".wav "$TITLE4".wav`

# Create info file

echo -e "Title: "$Release >> info.txt
echo -e "Date: "$DATE"\n" >> info.txt
echo -e "Tracks:" >> info.txt
echo -e "1- "$TITLE1 "-" $TIME1 >> info.txt
echo -e "2- "$TITLE2 "-" $TIME2 >> info.txt
echo -e "3- "$TITLE3 "-" $TIME3 >> info.txt
echo -e "4- "$TITLE4 "-" $TIME4"\n" >> info.txt
echo -e "Total time: " $TOTALTIME"\n" >> info.txt
echo -e "Programmed by: Miquel Parera\n\nDescription: LiveCoding,Algorithmic & Random AV Drones.\n\nSoftware Used:\nSound: SuperCollider (http://supercollider.github.io/)\nSound and Graphics: PureData (https://puredata.info/)\n\n
License: CC-BY-SA (http://creativecommons.org/licenses/by-sa/4.0/)\n
More info: http://musicnumbers.es/" >> info.txt


# make dirs

mkdir $Release

mkdir $Release"//"$Release"_mp3"
mkdir $Release"//"$Release"_flac"
mkdir $Release"//"$Release"_avi"

mkdir $Release"//"$Release"_mp3//images"
mkdir $Release"//"$Release"_flac//images"
mkdir $Release"//"$Release"_avi//images"

mkdir $Release"//"$Release"_mp3//code"
mkdir $Release"//"$Release"_flac//code"
mkdir $Release"//"$Release"_avi//code"



# cover

# make images

# screenshots

ORDER="ffmpeg -ss 00:03:00 -i "$TITLE1".avi -q:v 0 -vframes 1 "$TITLE1".jpg"
$ORDER

ORDER="ffmpeg -ss 00:03:00 -i "$TITLE2".avi -q:v 0 -vframes 1 "$TITLE2".jpg"
$ORDER

ORDER="ffmpeg -ss 00:03:00 -i "$TITLE3".avi -q:v 0 -vframes 1 "$TITLE3".jpg"
$ORDER

ORDER="ffmpeg -ss 00:03:00 -i "$TITLE4".avi -q:v 0 -vframes 1 "$TITLE4".jpg"
$ORDER

# cut

ORDER="convert "$TITLE1".jpg -crop 1435x220 "$TITLE1".jpg"
$ORDER

ORDER="convert "$TITLE2".jpg -crop 1435x220 "$TITLE2".jpg"
$ORDER

ORDER="convert "$TITLE3".jpg -crop 1435x220 "$TITLE3".jpg"
$ORDER

ORDER="convert "$TITLE4".jpg -crop 1435x220 "$TITLE4".jpg"
$ORDER

# montage

ORDER="montage -mode concatenate -tile 1x "$TITLE1"-0.jpg "$TITLE2"-0.jpg "$TITLE3"-0.jpg "$TITLE4"-0.jpg "$Release".jpg"
$ORDER

# gif

ORDER="convert -delay 15 -loop 0 "$TITLE1"-0.jpg "$TITLE1"-1.jpg "$TITLE1"-2.jpg "$TITLE1"-3.jpg "$TITLE1".gif"
$ORDER

ORDER="convert -delay 15 -loop 0 "$TITLE2"-0.jpg "$TITLE2"-1.jpg "$TITLE2"-2.jpg "$TITLE2"-3.jpg "$TITLE2".gif"
$ORDER

ORDER="convert -delay 15 -loop 0 "$TITLE3"-0.jpg "$TITLE3"-1.jpg "$TITLE3"-2.jpg "$TITLE3"-3.jpg "$TITLE3".gif"
$ORDER

ORDER="convert -delay 15 -loop 0 "$TITLE4"-0.jpg "$TITLE4"-1.jpg "$TITLE4"-2.jpg "$TITLE4"-3.jpg "$TITLE4".gif"
$ORDER

# cover

ORDER="convert "$Release".jpg -resize 170% "$Release"-cover1.jpg"
$ORDER

ORDER="convert "$Release"-cover1.jpg -crop 1429x1417+509+56 "$Release"-cover.jpg"
$ORDER

`convert "$Release"-cover.jpg -stroke black -fill white -linewidth 10 -draw 'rectangle 182,638 1247,778' "$Release"-cover.jpg`

`convert "$Release"-cover.jpg -gravity center -font Cabin-Bold -pointsize 40 -annotate 0 'Miquel Parera & Computer - '"$Release" "$Release"-cover.jpg`



# wav to mp3 and id3 tags

`lame -b 320 --tt "$TITLE1" --ta 'Miquel Parera & Computer' --ti "$Release"-cover.jpg --tl "$Release" --tn 1 --ty "$YEAR" --tc cc-by-sa "$TITLE1".wav`

`lame -b 320 --tt "$TITLE2" --ta 'Miquel Parera & Computer' --ti "$Release"-cover.jpg --tl "$Release" --tn 2 --ty "$YEAR" --tc cc-by-sa "$TITLE2".wav`

`lame -b 320 --tt "$TITLE3" --ta 'Miquel Parera & Computer' --ti "$Release"-cover.jpg --tl "$Release" --tn 3 --ty "$YEAR" --tc cc-by-sa "$TITLE3".wav`

`lame -b 320 --tt "$TITLE4" --ta 'Miquel Parera & Computer' --ti "$Release"-cover.jpg --tl "$Release" --tn 4 --ty "$YEAR" --tc cc-by-sa "$TITLE4".wav`


# wav to flac

`for x in *.wav;do flac --best $x;done;`


# id3 on flac

`id3v2 -a 'Miquel Parera & Computer' -A "$Release" -t "$TITLE1" -y "$YEAR" -c 'cc-by-sa' -T 1 "$TITLE1".flac`

`id3v2 -a 'Miquel Parera & Computer' -A "$Release" -t "$TITLE2" -y "$YEAR" -c 'cc-by-sa' -T 2 "$TITLE2".flac`

`id3v2 -a 'Miquel Parera & Computer' -A "$Release" -t "$TITLE3" -y "$YEAR" -c 'cc-by-sa' -T 3 "$TITLE3".flac`

`id3v2 -a 'Miquel Parera & Computer' -A "$Release" -t "$TITLE4" -y "$YEAR" -c 'cc-by-sa' -T 4 "$TITLE4".flac`


# join avi and wav

ORDER="ffmpeg -i "$TITLE1".wav -i "$TITLE1".avi -acodec copy -vcodec copy "$Release"/"$Release"_avi/"$TITLE1".avi"
$ORDER

ORDER="ffmpeg -i "$TITLE2".wav -i "$TITLE2".avi -acodec copy -vcodec copy "$Release"/"$Release"_avi/"$TITLE2".avi"
$ORDER

ORDER="ffmpeg -i "$TITLE3".wav -i "$TITLE3".avi -acodec copy -vcodec copy "$Release"/"$Release"_avi/"$TITLE3".avi"
$ORDER

ORDER="ffmpeg -i "$TITLE4".wav -i "$TITLE4".avi -acodec copy -vcodec copy "$Release"/"$Release"_avi/"$TITLE4".avi"
$ORDER


# move mp3 files

`for x in *.mp3;do mv $x "$Release"/"$Release"_mp3;done`

# move flac files

`for x in *.flac;do mv $x "$Release"/"$Release"_flac;done`

# copy image files

`cp "$Release"-cover.jpg "$Release"/"$Release"_flac/images`
`cp "$Release"-cover.jpg "$Release"/"$Release"_mp3/images`
`cp "$Release"-cover.jpg "$Release"/"$Release"_avi/images`

`cp "$Release".jpg "$Release"/"$Release"_flac/images`
`cp "$Release".jpg "$Release"/"$Release"_mp3/images`
`cp "$Release".jpg "$Release"/"$Release"_avi/images`

`cp "$TITLE1".jpg "$Release"/"$Release"_flac/images`
`cp "$TITLE2".jpg "$Release"/"$Release"_flac/images`
`cp "$TITLE3".jpg "$Release"/"$Release"_flac/images`
`cp "$TITLE4".jpg "$Release"/"$Release"_flac/images`

`cp "$TITLE1".jpg "$Release"/"$Release"_mp3/images`
`cp "$TITLE2".jpg "$Release"/"$Release"_mp3/images`
`cp "$TITLE3".jpg "$Release"/"$Release"_mp3/images`
`cp "$TITLE4".jpg "$Release"/"$Release"_mp3/images`

`cp "$TITLE1".jpg "$Release"/"$Release"_avi/images`
`cp "$TITLE2".jpg "$Release"/"$Release"_avi/images`
`cp "$TITLE3".jpg "$Release"/"$Release"_avi/images`
`cp "$TITLE4".jpg "$Release"/"$Release"_avi/images`

`cp "$TITLE1".gif "$Release"/"$Release"_flac/images`
`cp "$TITLE2".gif "$Release"/"$Release"_flac/images`
`cp "$TITLE3".gif "$Release"/"$Release"_flac/images`
`cp "$TITLE4".gif "$Release"/"$Release"_flac/images`

`cp "$TITLE1".gif "$Release"/"$Release"_mp3/images`
`cp "$TITLE2".gif "$Release"/"$Release"_mp3/images`
`cp "$TITLE3".gif "$Release"/"$Release"_mp3/images`
`cp "$TITLE4".gif "$Release"/"$Release"_mp3/images`

`cp "$TITLE1".gif "$Release"/"$Release"_avi/images`
`cp "$TITLE2".gif "$Release"/"$Release"_avi/images`
`cp "$TITLE3".gif "$Release"/"$Release"_avi/images`
`cp "$TITLE4".gif "$Release"/"$Release"_avi/images`

`rm *.jpg`
`rm *.avi`
`rm *.wav`
`rm *.gif`

tar -zcvf $CODEDATE.tar.gz -C $HOME/nxI .

`cp "$CODEDATE".tar.gz "$Release"/"$Release"_avi/code`
`cp "$CODEDATE".tar.gz "$Release"/"$Release"_mp3/code`
`cp "$CODEDATE".tar.gz "$Release"/"$Release"_flac/code`

rm $CODEDATE.tar.gz


`cp info.txt "$Release"/"$Release"_avi`
`cp info.txt "$Release"/"$Release"_mp3`
`cp info.txt "$Release"/"$Release"_flac`

`rm info.txt`

echo "RELEASE "$Release " COMPLETED"






